# Generated by Django 5.0.3 on 2024-08-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='plot_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
