# Generated by Django 5.0.3 on 2024-08-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarapp', '0002_textentry_plot_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textentry',
            name='plot_data',
        ),
    ]
